### ISSUE TITLE
无法正常访问安娜的档案

### ISSUE THREAD

**Issue by codyyuan413** [louiesun/Unofficial_Z_Access#2]
请大佬看一下安娜的档案网站，从工具里访问一开始可以正常打开，后面下载书或其他操作就不行了，然后就再也连不上了。请修复一下，谢谢。

**Comment by louiesun** [comment]
修不了。Anna's archieve你看到的本质上就是个引导页。
他的文件服务器散落在世界各地，比如俄罗斯之类的。
请注意，没有捐赠只能用SlowDownload。
如其名，SlowDownload非常慢。
我测试三个慢速地址可用性。据我所知，都没有被墙，可以用。
高速的懒得捐赠测试。
这个软件的主体（核心技术）早就完成了，主要是配置文件的问题。有能力可以试一下自己配置参照help.html。

**Comment by louiesun** [comment]
> 请大佬看一下安娜的档案网站，从工具里访问一开始可以正常打开，后面下载书或其他操作就不行了，然后就再也连不上了。请修复一下，谢谢。

另外，不同地区墙高不一样，报一下省市。

**Comment by codyyuan413** [comment]
> > 请大佬看一下安娜的档案网站，从工具里访问一开始可以正常打开，后面下载书或其他操作就不行了，然后就再也连不上了。请修复一下，谢谢。
> 
> 另外，不同地区墙高不一样，报一下省市。

山东

**Comment by louiesun** [comment]
> > > 请大佬看一下安娜的档案网站，从工具里访问一开始可以正常打开，后面下载书或其他操作就不行了，然后就再也连不上了。请修复一下，谢谢。
> > 
> > 
> > 另外，不同地区墙高不一样，报一下省市。
> 
> 山东

你现在是从软件首页进去连anna首页都进不去是吗。报错界面显示花费过长时间响应还是连接已重置？

**Comment by codyyuan413** [comment]
您好，今天上午下载了你的最新版本，下载了一个可以了，因为忙，没有多测试。


您程序又针对此问题优化吗？


谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月6日(周六) 下午2:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [louiesun/Unofficial_Z_Access] 无法正常访问安娜的档案 (Issue #2)




    
请大佬看一下安娜的档案网站，从工具里访问一开始可以正常打开，后面下载书或其他操作就不行了，然后就再也连不上了。请修复一下，谢谢。
  
另外，不同地区墙高不一样，报一下省市。
  
山东
  
你现在是从软件首页进去连anna首页都进不去是吗。报错界面显示花费过长时间响应还是连接已重置？

**Comment by louiesun** [comment]
> 您好，今天上午下载了你的最新版本，下载了一个可以了，因为忙，没有多测试。 您程序又针对此问题优化吗？ 谢谢
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月6日(周六) 下午2:53 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [louiesun/Unofficial_Z_Access] 无法正常访问安娜的档案 (Issue #2) 请大佬看一下安娜的档案网站，从工具里访问一开始可以正常打开，后面下载书或其他操作就不行了，然后就再也连不上了。请修复一下，谢谢。 另外，不同地区墙高不一样，报一下省市。 山东 你现在是从软件首页进去连anna首页都进不去是吗。报错界面显示花费过长时间响应还是连接已重置？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

没有，就改了个安卓指南？再观察一段时间吧，先close了，到时候再reopen。
不排除当时网站维护，但我不大想调查了。

**Comment by codyyuan413** [comment]
刚才在另外一台电脑上又试了一下。主页能打开，一搜索就出现这个界面。难道和电脑自身有关系？
还是和时间段有关系。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月6日(周六) 下午3:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [louiesun/Unofficial_Z_Access] 无法正常访问安娜的档案 (Issue #2)




  
您好，今天上午下载了你的最新版本，下载了一个可以了，因为忙，没有多测试。 您程序又针对此问题优化吗？ 谢谢
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年7月6日(周六) 下午2:53 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [louiesun/Unofficial_Z_Access] 无法正常访问安娜的档案 (Issue #2) 请大佬看一下安娜的档案网站，从工具里访问一开始可以正常打开，后面下载书或其他操作就不行了，然后就再也连不上了。请修复一下，谢谢。 另外，不同地区墙高不一样，报一下省市。 山东 你现在是从软件首页进去连anna首页都进不去是吗。报错界面显示花费过长时间响应还是连接已重置？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
没有，就改了个安卓指南？再观察一段时间吧，先close了，到时候再reopen。
 不排除当时网站维护，但我不大想调查了。

**Comment by louiesun** [comment]
> 刚才在另外一台电脑上又试了一下。主页能打开，一搜索就出现这个界面。难道和电脑自身有关系？ 还是和时间段有关系。

我没看到你说的界面，能不能直接github发一下？

**Comment by codyyuan413** [comment]
我附上了呀，看不到吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月6日(周六) 下午4:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [louiesun/Unofficial_Z_Access] 无法正常访问安娜的档案 (Issue #2)




  
刚才在另外一台电脑上又试了一下。主页能打开，一搜索就出现这个界面。难道和电脑自身有关系？ 还是和时间段有关系。
  
我没看到你说的界面，能不能直接github发一下？

**Comment by louiesun** [comment]
> 我附上了呀，看不到吗？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月6日(周六) 下午4:46 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [louiesun/Unofficial_Z_Access] 无法正常访问安娜的档案 (Issue #2) 刚才在另外一台电脑上又试了一下。主页能打开，一搜索就出现这个界面。难道和电脑自身有关系？ 还是和时间段有关系。 我没看到你说的界面，能不能直接github发一下？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我看不到。

**Comment by codyyuan413** [comment]
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=2801469858565267096 skey=@crypt_918f4ee1_d01139c837207e9733ef9572d440c30e mmweb_appid=wx_webfilehelper](https://github.com/louiesun/Unofficial_Z_Access/assets/127663423/559649f2-5de9-4735-b121-acf5a23bf724)

**Comment by louiesun** [comment]
> ![cgi-bin_mmwebwx-bin_webwxgetmsgimg_ MsgID=2801469858565267096 skey=@crypt_918f4ee1_d01139c837207e9733ef9572d440c30e mmweb_appid=wx_webfilehelper](https://private-user-images.githubusercontent.com/127663423/346263358-559649f2-5de9-4735-b121-acf5a23bf724.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNTYzOTYsIm5iZiI6MTcyMDI1NjA5NiwicGF0aCI6Ii8xMjc2NjM0MjMvMzQ2MjYzMzU4LTU1OTY0OWYyLTVkZTktNDczNS1iMTIxLWFjZjVhMjNiZjcyNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQwODU0NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2M2Y2RkZDg4MDViMzI1ZWYzOTRjN2EzOGJlZGVlZGM4Y2NmZTY2MjFhZWJlYTAzNTUxMTc5M2NhOTBjZjc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RLLSAqYvsxrWJ_tDIcXrh47YM0QHK-CaYh8C9PQIuoY)
啊这样啊你winR输入打cmd后Enter打开控制台。
输入
```
ping 172.64.145.17 -t
```
返回超过30行之后，CtrlC，告诉我出现了多少个请求超时。
我怀疑cloudflare的这个IP被你的运营商间歇性封锁了。
你有用过这个软件的zlibrary功能吗？（不是线路二），访问应该也不正常，对吧？

**Comment by louiesun** [comment]
呸，你换中文站了是吧，怪不得访问不了，默认配置我没打算支持中文站，因为我不常用anna。
这样设置: 同目录下有个DOMAINconfig.txt，在里面加一行，变成这样:

**Comment by louiesun** [comment]
由于` -origin-to-force-quic-on`不支持通配符，所以我这里不支持子域名自动配置，所以切记，不建议乱更改语言！！！！！！！！更改后务必参照（然而还未写完的）`help`自行更改配置！！！

**Comment by codyyuan413** [comment]
我第1次进去的时候是英文，我确实点击了右上角的中文，但是没有更改语言成功。 然后进行搜索就显示不出来搜索结果。


难道和我这个更改语言动作有关系哈？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月6日(周六) 下午5:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [louiesun/Unofficial_Z_Access] 无法正常访问安娜的档案 (Issue #2)




 
由于 -origin-to-force-quic-on不支持通配符，所以我这里不支持子域名自动配置，所以切记，不建议乱更改语言！！！！！！！！更改后务必参照（然而还未写完的）help自行更改配置！！！

**Comment by louiesun** [comment]
> 我第1次进去的时候是英文，我确实点击了右上角的中文，但是没有更改语言成功。 然后进行搜索就显示不出来搜索结果。 难道和我这个更改语言动作有关系哈？

就是这个原因……
是这样的，你改了语言之后，会自动跳转到`zh.annas-archive.se`这个子域名（本来是`annas-archive.se`）。
然后这个子域名是没有特殊配置的，所以GFW就生效了。
为什么默认配置里没有这个域名呢，~~因为我懒。~~

**Comment by codyyuan413** [comment]
谢谢大佬，原来是这样。


如何设置才能恢复呢？因为我现在再打开也显示不了主页了。 你刚才好像说加一行什么东西，我没看到具体的信息。


多谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月6日(周六) 下午5:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [louiesun/Unofficial_Z_Access] 无法正常访问安娜的档案 (Issue #2)




  
我第1次进去的时候是英文，我确实点击了右上角的中文，但是没有更改语言成功。 然后进行搜索就显示不出来搜索结果。 难道和我这个更改语言动作有关系哈？
  
就是这个原因……
 是这样的，你改了语言之后，会自动跳转到zh.annas-archive.se这个子域名（本来是annas-archive.se）。
 然后这个子域名是没有特殊配置的，所以GFW就生效了。
 为什么默认配置里没有这个域名呢，因为我懒。

**Comment by louiesun** [comment]
> 谢谢大佬，原来是这样。 如何设置才能恢复呢？因为我现在再打开也显示不了主页了。 你刚才好像说加一行什么东西，我没看到具体的信息。 多谢

下最新(V8)release吧。
我怕更你讲不清楚。

**Comment by codyyuan413** [comment]
多谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月6日(周六) 下午5:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [louiesun/Unofficial_Z_Access] 无法正常访问安娜的档案 (Issue #2)




  
谢谢大佬，原来是这样。 如何设置才能恢复呢？因为我现在再打开也显示不了主页了。 你刚才好像说加一行什么东西，我没看到具体的信息。 多谢
  
下最新(V8)release吧。
 我怕更你讲不清楚。

**Comment by codyyuan413** [comment]
大佬，最新版本中的LibGen链接打不开了，麻烦看一下，多谢了。
非常感谢好几个月以来的稳定访问z和安娜，多谢。







心飞扬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "louiesun/Unofficial_Z_Access"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月6日(星期六) 下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [louiesun/Unofficial_Z_Access] 无法正常访问安娜的档案 (Issue #2)





  
谢谢大佬，原来是这样。 如何设置才能恢复呢？因为我现在再打开也显示不了主页了。 你刚才好像说加一行什么东西，我没看到具体的信息。 多谢
  
下最新(V8)release吧。
 我怕更你讲不清楚。

**Comment by louiesun** [comment]
libgen下线维护了呗。你都看到nginx了就说明和服务器建立连接了。

> 大佬，最新版本中的LibGen链接打不开了，麻烦看一下，多谢了。 非常感谢好几个月以来的稳定访问z和安娜，多谢。 心飞扬 ***@***.*** &nbsp;

**Comment by codyyuan413** [comment]
收到，多谢了，那就等一下再试试。




心飞扬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "monthlyliaoyuan/Unofficial_Z_Access"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月25日(星期天) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [monthlyliaoyuan/Unofficial_Z_Access] 切换简中后无法正常访问安娜的档案 (Issue #2)





 
libgen下线维护了呗。你都看到nginx了就说明和服务器建立连接了。
  
大佬，最新版本中的LibGen链接打不开了，麻烦看一下，多谢了。 非常感谢好几个月以来的稳定访问z和安娜，多谢。 心飞扬 @.*** &nbsp;

**Comment by codyyuan413** [comment]
大佬，前几天发布的新版本，z、安娜、lib都打不开了呢。
里面的搜一搜&nbsp; &nbsp; 输入地址也打不开呢，是不是最近墙高了


心飞扬
***@***.***



&nbsp;

**Comment by louiesun** [comment]
> 大佬，前几天发布的新版本，z、安娜、lib都打不开了呢。
> 里面的搜一搜&nbsp; &nbsp; 输入地址也打不开呢，是不是最近墙高了
> 
> 
> 心飞扬
> ***@***.***
> 
> 
> 
> &nbsp;

不是啊，最新的版本完全换了个思路原理。我把配置什么的都删了。
google和x能打开吗？
可以先回退到老版本。。。

**Comment by louiesun** [comment]
v11那个版本可能要保证目录没有空格。因为aardio有个bug（现在修好了，我待会儿重新上传一下，顺便修掉libgen和anna）
然后zlib和anna是有适配的，libgen就没了。v10一直能用应该。

**Comment by louiesun** [comment]
是不是你的放dist的目录有空格？

**Comment by codyyuan413** [comment]
多谢 大佬修复。&nbsp; &nbsp; v11刚才确认了，路径没有空格，确实打不开页面。




心飞扬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "monthlyliaoyuan/Unofficial_Z_Access"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年2月14日(星期五) 上午9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [monthlyliaoyuan/Unofficial_Z_Access] 切换简中后无法正常访问安娜的档案 (Issue #2)



   
v11那个版本可能要保证目录没有空格。因为aardio有个bug（现在修好了，我待会儿重新上传一下，顺便修掉libgen和anna）
 然后zlib和anna是有适配的，libgen就没了。v10一直能用应该。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  louiesun left a comment (monthlyliaoyuan/Unofficial_Z_Access#2)
 
v11那个版本可能要保证目录没有空格。因为aardio有个bug（现在修好了，我待会儿重新上传一下，顺便修掉libgen和anna）
 然后zlib和anna是有适配的，libgen就没了。v10一直能用应该。

**Comment by louiesun** [comment]
customizre.bat试过了吗？应该就可以用google，x之类的

**Comment by codyyuan413** [comment]
customizre.bat启动 安装了一个组件什么的，启动了程序，但是还是无法打开googel等




心飞扬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "monthlyliaoyuan/Unofficial_Z_Access"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年2月14日(星期五) 上午9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [monthlyliaoyuan/Unofficial_Z_Access] 切换简中后无法正常访问安娜的档案 (Issue #2)



   
customizre.bat试过了吗？应该就可以用google，x之类的

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  louiesun left a comment (monthlyliaoyuan/Unofficial_Z_Access#2)
 
customizre.bat试过了吗？应该就可以用google，x之类的

**Comment by codyyuan413** [comment]
看到你发布的新版本了，z和安娜好用。但是libgen的地址libgen.rs已经无法访问了，好像libgen.gs可以访问。 如何获取这个域名的ip地址呢？


我尝试在三个txt文件里修改libgen.rs更改为libgen.gs不好用，我也查询了该域名对应的ip地址，同步修改了ip地址也不行呢






这样修改后使用aaradio软件生成exe后&nbsp; 还是无法打开libgen.gs


心飞扬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "monthlyliaoyuan/Unofficial_Z_Access"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年2月14日(星期五) 上午9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [monthlyliaoyuan/Unofficial_Z_Access] 切换简中后无法正常访问安娜的档案 (Issue #2)



   
customizre.bat试过了吗？应该就可以用google，x之类的

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  louiesun left a comment (monthlyliaoyuan/Unofficial_Z_Access#2)
 
customizre.bat试过了吗？应该就可以用google，x之类的

**Comment by louiesun** [comment]
啊，上cf了。
cf用quic。
配置是

```plaintext
104.21.41.17
libgen.g子域名.libgen.gs
```

如果有子域名在下面加

**Comment by codyyuan413** [comment]
我是小白，怎么看出是上了cf了呢？


再就是我截图中的104.21.41.17是真实的ip吗？  你txt里的所有ip地址都是域名对应的真实ip才行对吧？


我设置了txt中的libgen.g  libgen.gs信息，都还是访问不了。 


搞不明白这些。


使用下面的两种方式，都不行。


MAP libgen.g 104.21.41.17
MAP libgen.gs 104.21.41.17




心飞扬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "monthlyliaoyuan/Unofficial_Z_Access"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年2月15日(星期六) 晚上7:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [monthlyliaoyuan/Unofficial_Z_Access] 切换简中后无法正常访问安娜的档案 (Issue #2)



   
啊，上cf了。
 cf用quic。
 配置是
 104.21.41.17 libgen.g子域名.libgen.gs  
如果有子域名在下面加

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  louiesun left a comment (monthlyliaoyuan/Unofficial_Z_Access#2)
 
啊，上cf了。
 cf用quic。
 配置是
 104.21.41.17 libgen.g子域名.libgen.gs  
如果有子域名在下面加

**Comment by louiesun** [comment]
要改domain config.其他除了config.json都是自动根据domainconfig生成的，改了没用。

cf一般来说，，dnscheck.com或者别的查到的ip既有104开头又有172开头就是cf,或者有5个以上104开头。可以ipinfo.io或者whois365.com查ip归属

**Comment by louiesun** [comment]
不要看邮件，打错的东西邮件似乎无法及时更新我更正的内容

**Comment by codyyuan413** [comment]
非常感谢，那么晚了还回复我，早点休息大佬。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年2月15日(周六) 晚上10:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [monthlyliaoyuan/Unofficial_Z_Access] 切换简中后无法正常访问安娜的档案 (Issue #2)


   
要改domain config.其他除了config.json都是自动根据domainconfig生成的，改了没用。
 
cf一般来说，，dnscheck.com或者别的查到的ip既有104开头又有172开头就是cf,或者有5个以上104开头。可以ipinfo.io或者whois365.com查ip归属

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  louiesun left a comment (monthlyliaoyuan/Unofficial_Z_Access#2)
 
要改domain config.其他除了config.json都是自动根据domainconfig生成的，改了没用。
 
cf一般来说，，dnscheck.com或者别的查到的ip既有104开头又有172开头就是cf,或者有5个以上104开头。可以ipinfo.io或者whois365.com查ip归属

**Comment by codyyuan413** [comment]
都试过了，就这个libgen.gs不行，设置了都不好使，就是显示 已重置。&nbsp; libgen.gs这个域名是没问题的，是可以梯子访问的。麻烦大佬亲自出手修复吧。







心飞扬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "心飞扬"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年2月15日(星期六) 晚上10:58
***@***.******@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;回复：[monthlyliaoyuan/Unofficial_Z_Access] 切换简中后无法正常访问安娜的档案 (Issue #2)



非常感谢，那么晚了还回复我，早点休息大佬。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年2月15日(周六) 晚上10:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [monthlyliaoyuan/Unofficial_Z_Access] 切换简中后无法正常访问安娜的档案 (Issue #2)


   
要改domain config.其他除了config.json都是自动根据domainconfig生成的，改了没用。
 
cf一般来说，，dnscheck.com或者别的查到的ip既有104开头又有172开头就是cf,或者有5个以上104开头。可以ipinfo.io或者whois365.com查ip归属

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  louiesun left a comment (monthlyliaoyuan/Unofficial_Z_Access#2)
 
要改domain config.其他除了config.json都是自动根据domainconfig生成的，改了没用。
 
cf一般来说，，dnscheck.com或者别的查到的ip既有104开头又有172开头就是cf,或者有5个以上104开头。可以ipinfo.io或者whois365.com查ip归属

**Comment by louiesun** [comment]
等我回家

**Comment by louiesun** [comment]
等我回家

**Comment by louiesun** [comment]
https://github.com/monthlyliaoyuan/Unofficial_Z_Access/blob/master/DOMAINconfig.txt

我不知道你怎么改失败的。真的只加了一行。我在高中电脑上测过了
