### ISSUE TITLE
今天下了V9.3,换了DNS

### ISSUE THREAD

**Issue by sunnylang802** [louiesun/Unofficial_Z_Access#7]
louiesun 大大，我下载了V9.3,换了DNS，还是打不开zlibrary

**Comment by louiesun** [comment]
9.3不用换dns啊？
什么症状？
提供一下报错信息，谢谢。

**Comment by louiesun** [comment]
我的建议某个域名确定被墙后配置，不要改dns。

一些cdn上的文件容易慢。

**Comment by louiesun** [comment]
非常抱歉，由于目前您提供的信息过少，我无法帮助您诊断并解决问题。

如果48小时内您仍未回复，我将以not planned的方式关闭此issue。
