### ISSUE TITLE
关于发行缘由

### ISSUE THREAD

**Issue by xigxmmbc** [louiesun/Unofficial_Z_Access#8]
在2977名第十四届全国人大代表中，来自基层一线的代表再一次增多。一线工人、农民代表497名，占代表总数的16.7%，提高了约1个百分点，其中有56名农民工代表；专业技术人员代表634名，占代表总数21.3%，提高了0.7个百分点。
    在2007年召开的第十届全国人大五次会议上，《关于第十一届全国人民代表大会代表名额和选举问题的决定》明确规定，十一届全国人大代表中，来自一线的工人和农民代表人数应高于上一届。
https://www.12371.cn/2023/03/09/ARTI1678342348365440.shtml
    上海可能特殊一点吧。
    中华人民共和国是工人阶级领导的、以工农联盟为基础的人民民主专政的社会主义国家。这是宪法的第一条，我国有无数人为社会主义事业奋斗着，多些信心。

**Comment by xigxmmbc** [comment]
人大代表名单是公开的，身份也是可查的，但是没整理出来，得一个个查，我随机查了几个确实都是当官的或者老板

**Comment by xigxmmbc** [comment]
https://zh.wikipedia.org/wiki/%E7%AC%AC%E5%8D%81%E5%9B%9B%E5%B1%8A%E5%85%A8%E5%9B%BD%E4%BA%BA%E6%B0%91%E4%BB%A3%E8%A1%A8%E5%A4%A7%E4%BC%9A%E4%BB%A3%E8%A1%A8%E5%90%8D%E5%8D%95有人大代表的职务信息。确实感觉一线工人农民比统计的少。

**Comment by louiesun** [comment]
德国国家社会主义工人党也是社会主义党？

不是按名字来的。

本来工农是50%的哦，猜猜什么时候降下来的？

全民国家全民党迟早完蛋。

您哪里看出来工人阶级领导了？连8h工作制都实现不了。
________________________________
发件人: xigxmmbc ***@***.***>
发送时间: 2024年7月31日 11:33
收件人: louiesun/Unofficial_Z_Access ***@***.***>
抄送: Subscribed ***@***.***>
主题: [louiesun/Unofficial_Z_Access] 关于发行缘由 (Issue #8)


在2977名第十四届全国人大代表中，来自基层一线的代表再一次增多。一线工人、农民代表497名，占代表总数的16.7%，提高了约1个百分点，其中有56名农民工代表；专业技术人员代表634名，占代表总数21.3%，提高了0.7个百分点。
在2007年召开的第十届全国人大五次会议上，《关于第十一届全国人民代表大会代表名额和选举问题的决定》明确规定，十一届全国人大代表中，来自一线的工人和农民代表人数应高于上一届。


https://www.12371.cn/2023/03/09/ARTI1678342348365440.shtml
上海可能特殊一点吧。
中华人民共和国是工人阶级领导的、以工农联盟为基础的人民民主专政的社会主义国家。这是宪法的第一条，我国有无数人为社会主义事业奋斗着，多些信心。

―

**Comment by louiesun** [comment]
这个也许能让gpt整理。

让他以百度百科为数据源。
________________________________
发件人: xigxmmbc ***@***.***>
发送时间: 2024年7月31日 11:46
收件人: louiesun/Unofficial_Z_Access ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [louiesun/Unofficial_Z_Access] 关于发行缘由 (Issue #8)


人大代表名单是公开的，身份也是可查的，但是没整理出来，得一个个查，我随机查了几个确实都是当官的或者老板

―
